export const SkillData = [
    {
        skill_title:"HTML",
        percentage:"90%",
        type:"full-stack",
    },
    {
        skill_title:"CSS",
        percentage:"80%",
        type:"full-stack",
    },
    {
        skill_title:"JavaScript",
        percentage:"60%",
        type:"full-stack",
    },
    {
        skill_title:"React",
        percentage:"70%",
        type:"full-stack",
    }
]
